# Generated by Django 3.2.2 on 2021-05-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-date_added',)},
        ),
    ]
